### ISSUE TITLE
PyCrypto Obsolete

### ISSUE THREAD

**Issue by edmenendez** [Ziggeo/ZiggeoPythonSdk#19]
Currently, PyVimeo requires pycrypto 2.6.1 to be installed. That package is no longer maintained and the latest release is over 5 years old with lots of known security vulnerabilities (see https://github.com/dlitz/pycrypto/issues/173).

Instead you should look at https://pycryptodome.readthedocs.io/en/latest/src/vs_pycrypto.html

It's a drop-in replacement for pycrypto in most cases.

**Comment by Bane-D** [comment]
Hi Ed,

Thank you for letting us know. Will look into it and replace in the SDK.

Also thank you for linking the alternative as well :)

Regards,
Bane

**Comment by ibnutri** [comment]
Hi @edmenendez I've checked the SDK. You can have pycryptodome working on this SDK by removing currently installed pycrypto, and pip install the pycryptodome. Then the SDK work just like when using pycrypto.

It works like a drop-in replacement. Just make sure pycrypto is uninstalled it may interfere with pycryptodome installation.

**Comment by ibnutri** [comment]
Hi @edmenendez we have updated our the SDK requirement. So now it uses `pycryptodome` as the requirement.
