### ISSUE TITLE
Unable to use ZiggeoAuth.generate

### ISSUE THREAD

**Issue by 2019342a** [Ziggeo/ZiggeoPythonSdk#28]
Hi,

We have encountered the following issue when using `ZiggeoAuth.generate`

```
TypeError: Object type <class 'str'> cannot be passed to C code
```

This is caused by https://github.com/Ziggeo/ZiggeoPythonSdk/blob/72e29d088c6bcc2f9dc49ce02296fcb290b7e044/ZiggeoAuth.py#L10

and more specifically https://github.com/Ziggeo/ZiggeoPythonSdk/blob/72e29d088c6bcc2f9dc49ce02296fcb290b7e044/ZiggeoAuth.py#L24

I believe that both the `hashed_key` and the `plaintext` should be bytes but they are strings hence the error. Are we using it wrong or is this a bug?

**Comment by Bane-D** [comment]
Hi Theofilos,

I will close this issue, however please do let us know if you have tried the fix and if by some chance you are still experiencing any issues.

**Comment by 2019342a** [comment]
Hi @Bane-D. Thanks for the fix, it works as expected for us :raised_hands:

**Comment by Bane-D** [comment]
Awesome, glad to hear it, thank you for the update :)
